replicaCount: 2
deploymentStrategy: canary
image:
  repository: lehardocker/ecommerce-app
  pullPolicy: IfNotPresent
<<<<<<< Updated upstream
  tag: "dev-acd8652"
=======
  tag: "dev-21dab60"  

>>>>>>> Stashed changes
