---
# Source: my-app/templates/service.yaml
# 1. THE MAIN / ACTIVE SERVICE
# Always created for every environment (Dev, Staging, Prod)
apiVersion: v1
kind: Service
metadata:
  #name: staging-my-app-svc-active  # Matches 'stableService' or 'activeService'
  name: staging-my-app-svc-active
  namespace: staging
  labels:
    app.kubernetes.io/name: my-app
    environment: staging
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: my-app
    app.kubernetes.io/instance: staging-my-app
---
# Source: my-app/templates/service.yaml
# 2. THE PREVIEW / CANARY SERVICE
# Only created if we are NOT doing a simple "deployment"
apiVersion: v1
kind: Service
metadata:
  #name: staging-my-app-svc-preview # Matches 'canaryService' or 'previewService'
  name: staging-my-app-svc-preview
  namespace: staging
  labels:
    app.kubernetes.io/name: my-app
    environment: staging
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: my-app
    app.kubernetes.io/instance: staging-my-app
---
# Source: my-app/templates/analysis-template.yaml
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: staging-error-rate-check
  namespace: staging
spec:
  args:
    - name: jobName
  metrics:
    - name: error-rate-check
      interval: 30s
      count: 3
      successCondition: "result < 0.02"
      failureCondition: "result >= 0.05"
      consecutiveErrorLimit: 4
      retryOnError: true
      provider:
        prometheus:
          address: http://monitoring-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090
          query: |
            scalar(
              ( sum(rate(http_requests_total{job="my-app-staging",status=~"5.."}[1m])) or vector(0))
              /
              ( sum(rate(http_requests_total{job="my-app-staging" }[1m])) or vector(1))
            )
---
# Source: my-app/templates/httproute.yaml
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: staging-my-app-httproute
  namespace: staging
  labels:
    app.kubernetes.io/managed-by: helm
    app.kubernetes.io/part-of: ecommerce
    app.kubernetes.io/name: my-app
    environment: staging
    gitops.branch: staging
spec:
  parentRefs:
    - name: shared-gateway
      namespace: nginx-gateway
      sectionName: http-staging
  hostnames:
    - "staging.admedia.com"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: staging-my-app-svc-active
          port: 80
          weight: 100
        - name: staging-my-app-svc-preview
          port: 80
          weight: 0
---
# Source: my-app/templates/monitor.yaml
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: staging-my-app-podmonitor
  namespace: staging
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: my-app
  namespaceSelector:
    matchNames:
    - staging
  podMetricsEndpoints:
  - port: metrics
    interval: 30s
    path: /metrics
---
# Source: my-app/templates/rollout.yaml
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: staging-my-app
  namespace: staging
  labels:
    app.kubernetes.io/name: my-app
    environment: staging
spec:
  replicas: 2
  revisionHistoryLimit: 3

  # 🔥 Add stability controls
  progressDeadlineSeconds: 300
  abortScaleDownDelaySeconds: 30

  selector:
    matchLabels:
      app.kubernetes.io/name: my-app
      app.kubernetes.io/instance: staging-my-app

  template:
    metadata:
      labels:
        app.kubernetes.io/name: my-app
        app.kubernetes.io/instance: staging-my-app
    spec:
      containers:
        - name: my-app
          image: "lehardocker/ecommerce-app:stag-a27e7f2"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 3000

          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10

          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 20

  strategy:
    canary:
      canaryService: staging-my-app-svc-preview
      stableService: staging-my-app-svc-active

      trafficRouting:
        plugins:
          argoproj-labs/gateway-api:
            httpRoute: staging-my-app-httproute
      
      # 🔥 retain analysis history
      analysis:
        successfulRunHistoryLimit: 5
        unsuccessfulRunHistoryLimit: 5       

            
      steps:
        - setWeight: 20
        - analysis:
            templates:
            - templateName: staging-error-rate-check
            args:
            - name: jobName
              value: "my-app-staging"
        #- pause: { duration: 30s }

        - setWeight: 50        
        - analysis:
            templates:
            - templateName: staging-error-rate-check
            args:
            - name: jobName
              value: "my-app-staging"              
        #- pause: { duration: 30s }
        - setWeight: 100
