apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-image-updater-config
  namespace: argocd
  labels:
    app.kubernetes.io/managed-by: argocd
    app.kubernetes.io/part-of: ecommerce
    app.kubernetes.io/name: argocd-image-updater-config
    environment: dev
    gitops.branch: dev 
data:
  registries.conf: |
    registries:
      - name: Docker Hub
        prefix: docker.io
        api_url: https://registry-1.docker.io
        # Updated to match the secret we created earlier
        credentials: secret:argocd/dockerhub-creds
        defaultns: library
        default: true

  git.commit.user: "argocd-image-updater"
  git.commit.email: "argocd-image-updater@argoproj.io"

  git.commit-message-template: |  
    chore(image): update {{ .AppName }} 

    {{ range .AppChanges -}}
    Environment: {{ $.AppName }}
    Image: {{ .Image }}
    Previous Tag: {{ .OldTag }}
    New Tag: {{ .NewTag }}
    {{ end -}}
