apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cmp-cm
  namespace: argocd
data:
  avp.yaml: |
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: avp
    spec:
      allowConcurrency: true
      version: v1.0

      generate:
        command:
          - sh
          - "-c"
        args:
          - |
            helm template . \
            | /custom-tools/argocd-vault-plugin generate -

      discover:
        find:
          command:
            - sh
            - "-c"
          args:
            - test -f Chart.yaml
