apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: ecommerce-image-updater
  namespace: argocd
  labels:
    app.kubernetes.io/managed-by: argocd 
    app.kubernetes.io/part-of: ecommerce
    environment: gitops-dev
spec:  
  namespace: argocd
  applicationRefs:  
    #------------ DEVELOPMENT --------------------
    - namePattern: "dev-my-app"
      images:
        - alias: "app"
          imageName: "lehardocker/ecommerce-app"
          commonUpdateSettings:
            updateStrategy: "newest-build"
            allowTags: "regexp:^dev-.*"            
          manifestTargets:
            helm:
              name: "image.repository"
              tag: "image.tag"
      writeBackConfig:
        method: "git:secret:argocd/git-creds"
        gitConfig:
          repository: "https://github.com/sureshkumar-devops/ecommerce-gitops.git"
          branch: "dev"  # <--- Ensure this points to dev for all environments
          writeBackTarget: "environments/dev/values.yaml"          

   # --- STAGING ---
    - namePattern: "staging-my-app"
      images:
        - alias: "app"
          imageName: "lehardocker/ecommerce-app"
          commonUpdateSettings:
            updateStrategy: "newest-build"
            allowTags: "regexp:^stag.*"
          manifestTargets:
            helm:
              name: "image.repository"
              tag: "image.tag"
      writeBackConfig:
        method: "git:secret:argocd/git-creds"
        gitConfig:
          repository: "https://github.com/sureshkumar-devops/ecommerce-gitops.git"
          branch: "dev" # <--- FIXED: Now updates dev branch, staging folder
          writeBackTarget: "environments/staging/values.yaml"
          
  # --- PRODUCTION ---
    - namePattern: "prod-my-app"
      images:
        - alias: "app"
          imageName: "lehardocker/ecommerce-app"
          commonUpdateSettings:
            updateStrategy: "newest-build"
            allowTags: "regexp:^v[0-9]{4}+\\.[0-9]{2}+\\.[0-9]{2}-.*"            
          manifestTargets:
            helm:
              name: "image.repository"
              tag: "image.tag"
      writeBackConfig:
        method: "git:secret:argocd/git-creds"
        gitConfig:
          repository: "https://github.com/sureshkumar-devops/ecommerce-gitops.git"
          branch: "dev" # <--- FIXED: Now updates dev branch, prod folder
          writeBackTarget: "environments/prod/values.yaml"
      
