apiVersion: argocd-image-updater.argoproj.io/v2alpha1
kind: ImageUpdater
metadata:
  name: ecommerce-image-updater
  namespace: argocd
  labels:
    app.kubernetes.io/managed-by: helm
    app.kubernetes.io/part-of: ecommerce
    environment: gitops
spec:  
  namespace: argocd
  applicationRefs:  
    #------------ DEVELOPMENT --------------------
    - namePattern: "dev-my-app"
      images:
        - alias: "app"
          imageName: "lehardocker/ecommerce-app"
          commonUpdateSettings:
            updateStrategy: "newest-build"
            allowTags: "regexp:^dev-.*"            
          manifestTargets:
            helm:
              name: "image.repository"
              tag: "image.tag"
      writeBackConfig:
        method: "git:secret:argocd/git-creds"
        gitConfig:
          repository: "https://github.com/sureshkumar-devops/ecommerce-gitops.git"
          branch: "dev"
          writeBackTarget: "environments/dev/values.yaml"          
      metadata:
        labels:
          app.kubernetes.io/managed-by: argocd
          app.kubernetes.io/part-of: ecommerce
          environment: dev
          app.kubernetes.io/name: ecommerce-app
          gitops.branch: dev      

   # --- STAGING ---
    - namePattern: "staging-my-app"
      images:
        - alias: "app"
          imageName: "lehardocker/ecommerce-app"
          commonUpdateSettings:
            updateStrategy: "newest-build"
            allowTags: "regexp:^stag.*"
          manifestTargets:
            helm:
              name: "image.repository"
              tag: "image.tag"
      writeBackConfig:
        method: "git:secret:argocd/git-creds"
        gitConfig:
          repository: "https://github.com/sureshkumar-devops/ecommerce-gitops.git"
          branch: "staging"
          writeBackTarget: "environments/staging/values.yaml"
      metadata:
        labels:
          app.kubernetes.io/managed-by: argocd
          app.kubernetes.io/part-of: ecommerce
          environment: staging
          app.kubernetes.io/name: ecommerce-app
          gitops.branch: staging      

    # --- PRODUCTION ---
    - namePattern: "prod-my-app"
      images:
        - alias: "app"
          imageName: "lehardocker/ecommerce-app"
          commonUpdateSettings:
            updateStrategy: "newest-build"
            allowTags: "regexp:^v[0-9]{2}+\\.[0-9]{2}+\\.[0-9]{2}-.*"            
          manifestTargets:
            helm:
              name: "image.repository"
              tag: "image.tag"
      writeBackConfig:
        method: "git:secret:argocd/git-creds"
        gitConfig:
          repository: "https://github.com/sureshkumar-devops/ecommerce-gitops.git"
          branch: "master"
          writeBackTarget: "environments/prod/values.yaml"
      metadata:
        labels:
          app.kubernetes.io/managed-by: argocd
          app.kubernetes.io/part-of: ecommerce
          environment: production
          app.kubernetes.io/name: ecommerce-app
          gitops.branch: master  
      
