apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: ecommerce-image-updater  
  namespace: argocd
  labels:
    app.kubernetes.io/managed-by: helm
    app.kubernetes.io/part-of: ecommerce
    environment: gitops
spec:
  namespace: argocd        
  writeBackConfig:
    method: "git:secret:argocd/git-creds"
    gitConfig:
      repository: "https://github.com/sureshkumar-devops/ecommerce-gitops.git"
      branch: "dev"
      writeBackTarget: "helmvalues:../../environments/{{env}}/values.yaml"  
  applicationRefs:
    - namePattern: "{{env}}-my-app"      
      images:
        - alias: "app"
          imageName: "lehardocker/ecommerce-app"
          commonUpdateSettings:
            updateStrategy: "digest"
            allowTags: "regexp:^dev-.*"
            pullSecret: "secret:argocd/dockerhub-creds"  
            writeTag: |
              {{ if eq .Env "dev" }}{{ .Tag }}{{ end }}
              {{ if eq .Env "staging" }}stag-{{ .TagSuffix }}{{ end }}
              {{ if eq .Env "prod" }}v1.2.0-{{ .TagSuffix }}{{ end }}
          manifestTargets:
            helm:
              name: "image.repository"
              tag: "image.tag"

             

            
