apiVersion: v1
kind: Secret
metadata:
  name: my-app-secrets
  namespace: prod
  annotations:
    avp.kubernetes.io/path: "secret/data/prod/db"
type: Opaque
stringData:
  DB_USER: <db_username>
  DB_PASS: <db_password>
