replicaCount: 3
deploymentStrategy: bluegreen
image:
  repository: lehardocker/ecommerce-app
  pullPolicy: Always
  tag: "v1.2.0-cb77500"
service:
  port: 80 # external service port
  targetPort: 3000 # matches app inside container
containerPort: 3000 # matches app inside container
probePath: /
# Provide defaults for the probes
readinessProbe:
  initialDelaySeconds: 5
livenessProbe:
  initialDelaySeconds: 15
