apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ecommerce-applicationset
  namespace: argocd  
  annotations:
     argocd.argoproj.io/compare-options: ServerSideDiff=true
spec:
 generators:
 - list:
    elements:
    - env: dev
      namespace: dev
      branch: dev
    - env: staging
      namespace: staging
      branch: staging
    - env: prod      
      namespace: prod
      branch: master

 template:
   metadata:
    name: '{{env}}-my-app'
    labels:
      app.kubernetes.io/managed-by: argocd
      app.kubernetes.io/part-of: ecommerce
      environment: '{{env}}'
      app.kubernetes.io/name: ecommerce-app
      gitops.branch: '{{branch}}'  

   spec:
    ignoreDifferences:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      jsonPointers:
        - /spec/rules/0/backendRefs
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
    - group: argoproj.io
      kind: Rollout
      jsonPointers:
        - /spec/replicas

    project: default
    source:
     repoURL: https://github.com/sureshkumar-devops/ecommerce-gitops.git
     targetRevision: dev  # <--- Point to your dev branch
     path: charts/my-app  # <--- Use the shared templates
     
     #helm:
       #releaseName: "{{env}}-my-app" 
       #valueFiles:       
       #- "../../environments/{{env}}/values.yaml" # <--- Use dev or staging or prod env values
       #parameters:
       #- name: "env"
       #  value: "{{env}}"
     plugin:
       name: argocd-vault-plugin
       env:
       - name: ENV
         value: "{{env}}"
    destination:     
     server: https://kubernetes.default.svc
     namespace: '{{env}}'       
    syncPolicy: 
     automated:
       selfHeal: true
       prune: true
     syncOptions:
     -  CreateNamespace=true
     -  RespectIgnoreDifferences=true




