apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: multi-env
  namespace: argocd  
spec:
 generators:
 - list:
    elements:
    - env: dev
      namespace: dev
      branch: dev
    - env: staging
      namespace: staging
      branch: staging
    - env: prod
      branch: master
      namespace: prod

 template:
   metadata:
    name: '{{env}}-my-app'
    annotations:
      argocd-image-updater.argoproj.io/image-list: app=lehardocker/ecommerce-app
      argocd-image-updater.argoproj.io/app.helm.image-name: image.repository
      argocd-image-updater.argoproj.io/app.helm.image-tag: image.tag      
      #argocd-image-updater.argoproj.io/app.update-strategy: newest-build
      #argocd-image-updater.argoproj.io/app.allow-tags: regexp:^{{env}}-.*
      #argocd-image-updater.argoproj.io/write-back-method: git
   spec:
    project: default
    source:
     repoURL: https://github.com/sureshkumar-devops/ecommerce-gitops.git
     targetRevision: '{{branch}}'
     path: charts/my-app
     helm:
          valueFiles:
          - ../../environments/{{env}}/values.yaml
    destination:     
     server: https://kubernetes.default.svc
     namespace: '{{env}}'       
    syncPolicy:
     automated:
       selfHeal: true
       prune: true
     syncOptions:
     - CreateNamespace=true
