{{- if .Values.analysis.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: {{ .Values.env }}-error-rate-check
  namespace: {{ .Values.env }}
spec:
  args:
  - name: metricName
  - name: jobName  # <--- Add this argument
  metrics:
  - name: {{ printf "{{args.metricName}}" | quote }}
    interval: {{ .Values.analysis.interval }}
    count: {{ .Values.analysis.count }}
    successCondition: {{ printf "result < %v" .Values.analysis.successThreshold | quote }}
    failureCondition: {{ printf "result >= %v" .Values.analysis.failureThreshold | quote }}
    provider:
      prometheus:
        address: {{ .Values.analysis.prometheus.address }}
        query: |
          {{- if eq .Values.env "staging" }}
          sum(rate(http_requests_total{job="{{`{{args.jobName}}` }}",status=~"5.."}[1m]))
          / sum(rate(http_requests_total{job="{{`{{args.jobName}}` }}"}[1m]))
          {{- else if eq .Values.env "prod" }}
          sum(rate(nginx_ingress_controller_requests{ingress="{{ .Values.analysis.prometheus.ingress }}",status=~"5.."}[1m]))
          / sum(rate(nginx_ingress_controller_requests{ingress="{{ .Values.analysis.prometheus.ingress }}"}[1m]))
          {{- end }}
{{- end }}

