{{- if and (eq .Values.env "dev") .Values.analysis.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: AnalysisRun
metadata:
  generateName: {{ include "my-app.fullname" . }}-health-check-
  namespace: {{ .Values.env }}
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  analysisTemplate:
    - name: {{ .Values.env }}-app-health-check
  args:
    - name: jobName
      value: {{ .Values.jobName | default "my-app" | quote }}
{{- end }}
