{{- if and (eq .Values.env "dev") .Values.analysis.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: AnalysisRun
metadata:
  generateName: {{ .Values.env }}-health-check
  namespace: {{ .Values.env }}
spec:
 analysisTemplate:
   name: {{ .Values.env }}-app-health-check
 arguments:
   - name: jobName
     value: {{ .Values.jobName | default "my-app" | quote }}
{{- end }}

