apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: {{ .Values.env }}-error-rate-check
  namespace: {{ .Values.env }}
spec:
  args:
    - name: jobName
  metrics:
    - name: error-rate-check
      interval: {{ .Values.analysis.interval }}
      count: {{ .Values.analysis.count }}
      successCondition: "result < {{ .Values.analysis.successThreshold }}"
      failureCondition: "result >= {{ .Values.analysis.failureThreshold }}"
      consecutiveErrorLimit: 4
      retryOnError: {{ .Values.analysis.retryOnError | default false }}
      provider:
        prometheus:
          address: {{ .Values.analysis.prometheus.address }}
          query: |
            {{- if eq .Values.env "staging" }}
            scalar(
              ( sum(rate(http_requests_total{job="{{ include "my-app.jobName" . }}",status=~"5.."}[1m])) or vector(0))
              /
              ( sum(rate(http_requests_total{job="{{ include "my-app.jobName" . }}" }[1m])) or vector(1))
            )
            {{- else if eq .Values.env "prod" }}
            scalar(
              ( sum(rate(nginx_http_requests_total{host="{{ include "my-app.jobName" . }}",status=~"5.."}[1m])) or vector(0))
              /
              ( sum(rate(nginx_http_requests_total{host="{{ include "my-app.jobName" . }}" }[1m])) or vector(1))
            )
            {{- else if eq .Values.env "dev" }}
            scalar(
              ( sum(rate(http_requests_total{job="{{ include "my-app.jobName" . }}",status=~"5.."}[30s])) or vector(0))
              /
              ( sum(rate(http_requests_total{job="{{ include "my-app.jobName" . }}" }[30s])) or vector(1))
            )
            {{- else }}
            scalar(
              ( sum(rate(http_requests_total{job="{{ include "my-app.jobName" . }}",status=~"5.."}[1m])) or vector(0))
              /
              ( sum(rate(http_requests_total{job="{{ include "my-app.jobName" . }}" }[1m])) or vector(1))
            )
            {{- end }}
