apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-image-updater-config
  namespace: argocd
data:
  registries.conf: |
    registries:
      - name: Docker Hub
        prefix: docker.io
        api_url: https://registry-1.docker.io
        # Updated to match the secret we created earlier
        credentials: pullsecret:argocd/dockerhub-creds
        defaultns: library
        default: true

  git.user: "argocd-image-updater"
  git.email: "argocd@example.com"

  git.commit-message-template: |  
    chore(image): update {{ .AppName }} 

    {{ range .AppChanges -}}
    Image: {{ .Image }}
    Previous Tag: {{ .OldTag }}
    New Tag: {{ .NewTag }}
    {{ end -}}
