{{- if eq .Values.deploymentStrategy "deployment" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "my-app.fullname" . }}  
  labels:     
    app.kubernetes.io/managed-by: helm
    app.kubernetes.io/part-of: ecommerce
    app.kubernetes.io/name: my-app
    environment: {{ .Values.env }}
    gitops.branch: {{ .Values.gitopsBranch }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:        
      app.kubernetes.io/name: {{ .Chart.Name }}
  template:
    metadata:
     labels:
      app.kubernetes.io/name: {{ .Chart.Name }} 
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http-deploy
              containerPort: {{ .Values.containerPort }}
          readinessProbe:
            httpGet:
              path: {{ .Values.probePath }}
              port: {{ .Values.containerPort }}
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds | default 10 }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds | default 2 }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds | default 10 }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold | default 3 }}
          livenessProbe:
            httpGet:
              path: {{ .Values.probePath }}
              port: {{ .Values.containerPort }}
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds | default 20 }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds | default 2 }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds | default 10 }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold | default 3 }}
{{- end }}
