{{- if eq .Values.deploymentStrategy "deployment" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "my-app.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: my-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.containerPort }}
          readinessProbe:
            httpGet:
              path: {{ .Values.probePath }}
              port: {{ .Values.containerPort }}
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds | default 10 }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds | default 2 }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds | default 10 }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold | default 3 }}
          livenessProbe:
            httpGet:
              path: {{ .Values.probePath }}
              port: {{ .Values.containerPort }}
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds | default 20 }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds | default 2 }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds | default 10 }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold | default 3 }}
{{- end }}
