{{- $creds := .Values.imageCredentials | default dict -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $creds.name | default "dockerhub-creds" }}
  namespace: argocd
  labels:
    argocd-image-updater.argoproj.io/secret-type: pullsecret
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
     "auths": {
       "https://index.docker.io/v1/": {
       "username": {{ $creds.username | quote }},
       "password": {{ $creds.password | quote }},
       "auth": {{ $creds.auth | quote }}
        },
       "https://registry-1.docker.io": {
       "username": {{ $creds.username | quote }},
       "password": {{ $creds.password | quote }},
       "auth": {{ $creds.auth | quote }} }
      }    
    }
