{{- if .Values.httpRoute.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Values.env }}-my-app-httproute
  namespace: {{ .Values.env }}
  labels:
    app.kubernetes.io/managed-by: helm
    app.kubernetes.io/part-of: ecommerce
    app.kubernetes.io/name: {{ .Chart.Name }}
    environment: {{ .Values.env }}
    gitops.branch: {{ .Values.gitopsBranch | default "master" }}
spec:
  parentRefs:
    - name: {{ .Values.httpRoute.parentGatewayName }}
      {{- if .Values.httpRoute.parentGatewayNamespace }}
      namespace: {{ .Values.httpRoute.parentGatewayNamespace }}
      {{- end }}
      {{- if .Values.httpRoute.parentGatewaySectionName }}
      sectionName: {{ .Values.httpRoute.parentGatewaySectionName }}
      {{- end }}
  hostnames:
    {{- range .Values.httpRoute.hostnames }}
    - {{ . | quote }}
    {{- end }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        # Main Backend (Dev, Staging, Prod)
        - name: {{ include "my-app.serviceNameActive" . }}
          port: {{ .Values.service.port }}
          weight: 100

        # Conditional Secondary Backend
        {{- if eq .Values.deploymentStrategy "canary" }}
        - name: {{ include "my-app.serviceNameCanary" . }}
          port: {{ .Values.service.port }}
          weight: 0
        {{- else if eq .Values.deploymentStrategy "bluegreen" }}
        - name: {{ include "my-app.serviceNamePreview" . }}
          port: {{ .Values.service.port }}
          weight: 0
        {{- end }}    
{{- end }}
