{{- if and .Values.monitoring.enabled (eq .Values.monitoring.type "servicemonitor") }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "my-app.fullname" . }}-servicemonitor
  namespace: {{ .Release.Namespace }}
  labels:
    release: {{ .Values.monitoring.prometheusRelease }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "my-app.fullname" . }}
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  endpoints:
  - port: {{ .Values.monitoring.portName }}
    interval: {{ .Values.monitoring.interval }}
    path: {{ .Values.monitoring.path }}
{{- else if and .Values.monitoring.enabled (eq .Values.monitoring.type "podmonitor") }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "my-app.fullname" . }}-podmonitor
  namespace: {{ .Release.Namespace }}
  labels:
    release: {{ .Values.monitoring.prometheusRelease }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "my-app.fullname" . }}
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  podMetricsEndpoints:
  - port: {{ .Values.monitoring.portName }}
    interval: {{ .Values.monitoring.interval }}
    path: {{ .Values.monitoring.path }}
{{- end }}
