{{- if and (ne .Values.deploymentStrategy "deployment") .Values.rollout.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ include "my-app.fullname" . }}
  namespace: {{ .Values.env }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    environment: {{ .Values.env }}
  annotations:
    notifications.argoproj.io/subscribe.on-analysis-failed.slack: devops-alerts
    notifications.argoproj.io/subscribe.on-rollout-aborted.slack: devops-alerts
    notifications.argoproj.io/subscribe.on-rollout-success.slack: devops-alerts
    notifications.argoproj.io/subscribe.on-rollout-completed.slack: devops-alerts 
spec:
  replicas: {{ .Values.replicaCount | default 2 }}
  revisionHistoryLimit: 2

  # 🔥 Add stability controls
  progressDeadlineSeconds: 300
  abortScaleDownDelaySeconds: 30

  selector:
    matchLabels:
      {{- include "my-app.selectorLabels" . | nindent 6 }}

  template:
    metadata:
      labels:
        {{- include "my-app.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | default "Always" }}
          ports:
            - name: {{ .Values.monitoring.portName | default "metrics" }} # Change 'http' to this
              containerPort: {{ .Values.service.targetPort | default 3000 }}

          readinessProbe:
            httpGet:
              path: {{ .Values.probePath | default "/" }}
              port: {{ .Values.containerPort | default 3000 }}
            initialDelaySeconds: 10

          livenessProbe:
            httpGet:
              path: {{ .Values.probePath | default "/" }}
              port: {{ .Values.containerPort | default 3000 }}
            initialDelaySeconds: 20

  strategy:
{{- if eq .Values.deploymentStrategy "canary" }}
    canary:
      abortScaleDownDelaySeconds: 30  # cleanup failed canary
      canaryService: {{ .Values.service.previewName }}
      stableService: {{ .Values.service.name }}
      trafficRouting:
       plugins:
         argoproj-labs/gatewayAPI:
           httpRoute: {{ .Values.env }}-my-app-httproute
           namespace: {{ .Values.env }}       
      steps:
        # 🔹 STEP 1
        - setWeight: 20
        - pause: { duration: 1m } 
{{- if .Values.analysis.enabled }}
        - analysis:
          templates:
          - templateName: {{ .Values.env }}-app-health-check 
          args:
          - name: jobName
            value: {{ include "my-app.jobName" . | quote }}
{{- end }}
        # 🔹 STEP 2
        - setWeight: 50
        - pause: { duration: 1m }
{{- if .Values.analysis.enabled }}        
        - analysis:
          templates:
          - templateName: {{ .Values.env }}-app-health-check
          args:
          - name: jobName
            value: {{ include "my-app.jobName" . | quote }}
{{- end }}              
        # 🔹 STEP 3 (FINAL)
        - setWeight: 100
        - pause: { duration: 2m }
{{- if .Values.analysis.enabled }}
        - analysis:
          templates:
          - templateName: {{ .Values.env }}-app-health-check
          args:
          - name: jobName
            value: {{ include "my-app.jobName" . | quote }}
{{- end }}
{{- end }}

{{- if eq .Values.deploymentStrategy "bluegreen" }}
    blueGreen:
      activeService: {{ .Values.service.name }}
      previewService: {{ .Values.service.previewName }}
      autoPromotionEnabled: true
{{- if .Values.analysis.enabled }}
      prePromotionAnalysis:
        templates:
        - templateName: {{ .Values.env }}-app-health-check
        args:
        - name: jobName
          value: {{ include "my-app.jobName" . | quote }}
      postPromotionAnalysis:
        templates:
        - templateName: {{ .Values.env }}-app-health-check
        args:
        - name: jobName
          value: {{ include "my-app.jobName" . | quote }}
{{- end }}
{{- end }}
{{- end }}
