apiVersion: v1
kind: ConfigMap
metadata:
  name: argo-rollouts-config
  namespace: argo-rollouts
  labels:
    app.kubernetes.io/component: rollouts-controller
    app.kubernetes.io/name: argo-rollouts
    app.kubernetes.io/part-of: argo-rollouts
data:
  trafficRouterPlugins: |
    - name: "argoproj-labs/gateway-api"
      apiVersion: gateway.networking.k8s.io/v1
      kind: HTTPRoute
      namespace: {{ .Values.httpRoute.parentGatewayNamespace }}
      sectionName: {{ .Values.httpRoute.parentGatewaySectionName }}

  prometheus: |
    address: {{ .Values.analysis.prometheus.address }}
    timeout: 30

  features: |
    RetryAnalysis: {{ .Values.features.RetryAnalysis }}
    ExperimentTrafficRouting: {{ .Values.features.ExperimentTrafficRouting }}
