{{- if and (ne .Values.deploymentStrategy "deployment") .Values.rollout.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ include "my-app.fullname" . }}
  namespace: {{ .Values.env }}
  labels:
    {{- include "my-app.labels" . | nindent 4 }}
  annotations:
    notifications.argoproj.io/subscribe.on-analysis-failed.slack: devops-alerts
    notifications.argoproj.io/subscribe.on-rollout-aborted.slack: devops-alerts
    notifications.argoproj.io/subscribe.on-rollout-success.slack: devops-alerts
    notifications.argoproj.io/subscribe.on-rollout-completed.slack: devops-alerts
spec:
  replicas: {{ .Values.replicaCount | default 2 }}
  revisionHistoryLimit: 3
  progressDeadlineSeconds: 300  

  selector:
    matchLabels:
      {{- include "my-app.selectorLabels" . | nindent 6 }}

  # --- STRATEGY BLOCK ---
  strategy:
{{- if eq .Values.deploymentStrategy "canary" }}
    canary:
      #successfulJobsHistoryLimit: 2
      #failedJobsHistoryLimit: 1
      abortScaleDownDelaySeconds: 30
      canaryService: {{ include "my-app.serviceNameCanary" . }}
      stableService: {{ include "my-app.serviceNameActive" . }}
      trafficRouting:
        plugins:
          argoproj-labs/gatewayAPI:
            httpRoute: {{ .Values.env }}-my-app-httproute
            namespace: {{ .Values.env }}
      steps:
        - setWeight: 20
        - pause: { duration: 1m }
{{- if .Values.analysis.enabled }}
        - analysis:
            templates:
              - templateName: {{ .Values.env }}-app-health-check
            args:
              - name: jobName
                value: {{ include "my-app.jobName" . | quote }}
{{- end }}
        - setWeight: 50
        - pause: { duration: 1m }
{{- if .Values.analysis.enabled }}
        - analysis:
            templates:
              - templateName: {{ .Values.env }}-app-health-check
            args:
              - name: jobName
                value: {{ include "my-app.jobName" . | quote }}
{{- end }}
        - setWeight: 100
{{- end }}

{{- if eq .Values.deploymentStrategy "bluegreen" }}
    blueGreen:
      #successfulJobsHistoryLimit: 2
      #failedJobsHistoryLimit: 1
      activeService: {{ include "my-app.serviceNameActive" . }}
      previewService: {{ include "my-app.serviceNamePreview" . }}
      autoPromotionEnabled: true
{{- if .Values.analysis.enabled }}
      prePromotionAnalysis:
        templates:
          - templateName: {{ .Values.env }}-app-health-check
        args:
          - name: jobName
            value: {{ include "my-app.jobName" . | quote }}
      postPromotionAnalysis:
        templates:
          - templateName: {{ .Values.env }}-app-health-check
        args:
          - name: jobName
            value: {{ include "my-app.jobName" . | quote }}
{{- end }}
{{- end }}

  # --- POD TEMPLATE ---
  template:
    metadata:
      labels:
        {{- include "my-app.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | default "Always" }}
          ports:
            - name: {{ .Values.monitoring.portName | default "metrics" }}
              containerPort: {{ .Values.service.targetPort | default 3000 }}

          # ✅ REQUIRED FOR HPA
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu | default "100m" }}
              memory: {{ .Values.resources.requests.memory | default "128Mi" }}
            limits:
              cpu: {{ .Values.resources.limits.cpu | default "200m" }}
              memory: {{ .Values.resources.limits.memory | default "256Mi" }}


          readinessProbe:
            httpGet:
              path: {{ .Values.probePath | default "/" }}
              port: {{ .Values.containerPort | default 3000 }}
            initialDelaySeconds: 10
          livenessProbe:
            httpGet:
              path: {{ .Values.probePath | default "/" }}
              port: {{ .Values.containerPort | default 3000 }}
            initialDelaySeconds: 20
{{- end }}

