{{- if eq .Values.deploymentStrategy "bluegreen" }}

apiVersion: v1
kind: Service
metadata:
  name: my-app-preview

spec:
  selector:
    app: my-app

  ports:
  - port: {{ .Values.service.Port }}
    targetPort: {{ .Values.service.targetPort }}


{{- end }}
