{{- if eq .Values.deploymentStrategy "bluegreen" }}
apiVersion: v1
kind: Service
metadata:
 # Matches 'activeService' in rollout-bluegreen.yaml
  name: {{ .Release.Namespace }}-svc-{{ .Chart.Name }}-active
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
spec:
  selector:  
    app.kubernetes.io/name: {{ .Chart.Name }}  
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.service.port | default 80 }}
      targetPort: {{ .Values.containerPort | default 3000 }}
      protocol: TCP
      name: http
{{- end }}
