{{- if eq .Values.deploymentStrategy "deployment" }}
apiVersion: v1
kind: Service
metadata:
  name:  {{ .Values.service.name }} 
  namespace: {{ .Values.env }}  
  labels:
    app.kubernetes.io/managed-by: helm
    app.kubernetes.io/part-of: ecommerce
    app.kubernetes.io/name: {{ .Chart.Name }}
    environment: {{ .Values.env }}
    gitops.branch: {{ .Values.gitopsBranch }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }} 
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "my-app.selectorLabels" . | nindent 4 }}
{{- end }}
