{{- if eq .Values.deploymentStrategy "bluegreen" }}
apiVersion: v1
kind: Service
metadata:
   # Matches 'previewService' in rollout-bluegreen.yaml
  name: {{ .Values.env }}-svc-{{ .Chart.Name }}-preview
  namespace: {{ .Values.env }} 
  labels:
    app.kubernetes.io/managed-by: helm
    app.kubernetes.io/part-of: ecommerce
    app.kubernetes.io/name: {{ .Chart.Name }}
    environment: {{ .Values.env }}
    gitops.branch: {{ .Values.gitopsBranch }}  
spec:
  selector:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  type: {{ .Values.service.type | default "ClusterIP" }}  
  ports:  
  - port: {{ .Values.service.port | default 80 }}
    targetPort: {{ .Values.containerPort | default 3000 }}
    protocol: TCP
    name: http  
{{- end }}
