{{- if eq .Values.deploymentStrategy "bluegreen" }}
apiVersion: v1
kind: Service
metadata:
   # Matches 'previewService' in rollout-bluegreen.yaml
  name: {{ .Release.Namespace }}-svc-{{ .Chart.Name }}-preview
  labels:
    {{- include "my-app.labels" . | nindent 4 }}
spec:
  selector:
    app: my-app
  type: {{ .Values.service.type | default "ClusterIP" }}  
  ports:  
  - port: {{ .Values.service.port | default 80 }}
    targetPort: {{ .Values.containerPort | default 3000 }}
    protocol: TCP
    name: http  
{{- end }}
