# --- Global Environment Identifier ---
env: dev
gitopsBranch: dev
# --- Deployment / Rollout Settings ---
replicaCount: 1
deploymentStrategy: deployment
image:
  repository: lehardocker/ecommerce-app
  tag: "dev-492c39c" # Image Updater will replace this with dev-<sha>
  pullPolicy: Always
# --- Service Configuration ---  
service:
  enabled: true
  name: dev-my-app-svc-active
  previewName: dev-my-app-svc-preview
  port: 80 # external service port
  targetPort: 3000 # matches app inside container
# --- Container & Resource Settings ---
containerPort: 3000 # matches app inside container
# --- Probe Settings ---
# ✅ health check
probePath: /
readinessProbe:
  initialDelaySeconds: 5
  timeoutSeconds: 2
  periodSeconds: 10
  failureThreshold: 3
livenessProbe:
  initialDelaySeconds: 15
  timeoutSeconds: 2
  periodSeconds: 10
  failureThreshold: 3
analysis:
  enabled: true
  interval: 15s
  count: 2 # Reduced from 3 to 2 for faster Dev cycles
  # thresholds
  traffic:
    min: 5 # very low traffic allowed    
  error:
    threshold: 0.05 # 5% allowed <5% errors
    consecutiveLimit: 3
  success:
    threshold: 0.95 # >95% success
  latency:
    Threshold: 1.0 # 1 sec allowed
  prometheus:
    #address: http://prometheus-operated.monitoring.svc.cluster.local:9090
    address: http://monitoring-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090
    #job: dev-my-app-job # Usually dev jobs have a -dev suffix
httpRoute:
  enabled: true
  parentGatewayName: shared-gateway
  parentGatewayNamespace: nginx-gateway
  parentGatewaySectionName: http-dev
  hostnames:
  - dev.admedia.com
features:
  RetryAnalysis: true
  ExperimentTrafficRouting: true
# --- ServiceMonitor in prod for stable, service‑based scraping ---
monitoring:
  enabled: false
  type: servicemonitor
  prometheusRelease: prometheus
  portName: metrics
  interval: 30s
  path: /metrics
rollout:
  enabled: false # no Rollout, just Deployment
# ✅ REQUIRED FOR HPA
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi
# ✅ HPA CONFIG
hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50
  targetMemoryUtilizationPercentage: 50
