# --- Global Environment Identifier ---

env: dev
# --- Deployment / Rollout Settings ---
replicaCount: 1
deploymentStrategy: deployment
image:
  repository: lehardocker/ecommerce-app
  pullPolicy: Always
  tag: "dev-cee7768" # Image Updater will replace this with dev-<sha>
# --- Service Configuration ---    
service:
  name: dev-svc-my-app
  port: 80 # external service port
  targetPort: 3000 # matches app inside container
# --- Container & Probe Settings ---
containerPort: 3000 # matches app inside container
probePath: /
# Provide defaults for the probes
readinessProbe:
  initialDelaySeconds: 5
livenessProbe:
  initialDelaySeconds: 15
# --- Gateway API Configuration (The Missing Parts) ---
gateway:
  enabled: true
  className: nginx # Matches your GatewayClass name
httpRoute:
  enabled: true
  parentGatewayName: dev-gateway
  hostnames:
  - dev.admedia.com
# --- Cluster-wide Resources ---
gatewayClass:
  create: true # Set to true in dev, false in staging/prod to avoid duplicates
